version: '3'
services:
  postgres:
    image: postgres:10-alpine
    restart: always
    # 任意のパスワード
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: testdb
    # ホスト側は任意のディレクトリ
    volumes:
      - testdb:/d/docker/postgres/data
    # ホスト側は任意のポート
    ports:
      - 5432:5432

volumes:
  testdb:
    external: true